---
title: "Using Simphony to Benchmark Rhythmic Detection Methods"
author: "Jordan Singer"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, message = FALSE}
library(data.table)
library(ggplot2)
library(knitr)
library(limma)
library(precrec)
library(simphony)
```

```{r, message = FALSE}
set.seed(42)
exprGroups = data.table(fracGenes = c(0.5, 0.5), base = 0,
                        amp = c(0, 1.2), phase = 0)
simGse = simulateExprData(exprGroups, nGenes = 1000)
kable(exprGroups)
```

```{r, message = FALSE, fig.width = 6}
nonRhythmicGene = simGse$geneMetadata$gene[simGse$geneMetadata$group == 1][1]
rhythmicGene = simGse$geneMetadata$gene[simGse$geneMetadata$group == 2][1]
combinedExpr = data.table(expression = c(simGse$exprData[nonRhythmicGene,], simGse$exprData[rhythmicGene,]),
                          time = simGse$sampleMetadata$time,
                          cond = c(rep('nonRhythmic', ncol(simGse$exprData)), rep('rhythmic', ncol(simGse$exprData))))

ggplot(combinedExpr, aes(x = time, y = expression, color = cond)) +
  geom_point() +
  coord_cartesian(xlim = c(0, 24), ylim = c(-3, 3)) +
  labs(x = 'time (h)', y = 'expression', title = 'Sample simulated time courses', color = 'rhythmic condition')
```

```{r, message = FALSE}
sm = data.table(simGse$sampleMetadata)
sm[, time_cos := cos(time * 2*pi / 24)]
sm[, time_sin := sin(time * 2*pi / 24)]
emat = simGse$exprData
design = model.matrix(~ time_cos + time_sin, data = sm)
fit = lmFit(emat, design)
fit = eBayes(fit, trend = TRUE)

gm = data.table(simGse$geneMetadata)
drLimma = topTable(fit, coef = 2:3, number = Inf)
drLimma$gene = rownames(drLimma)
gm = merge(gm, drLimma)
```

```{r, message = FALSE}
ggplot(gm, aes(x = factor(ifelse(group == 1, 'Non Rhythmic', 'Rhythmic')), y = P.Value)) +
  geom_violin() +
  labs(x = NULL, y = expression(p[rhy]), title = 'limma p-values of rhythmicity')
```

```{r, message = FALSE}
rocprc = evalmod(scores = -log10(gm$P.Value), labels = ifelse(gm$group == 1, FALSE, TRUE))
autoplot(rocprc, 'ROC')
```
