version: 2
jobs:
  build:
    docker:
      - image: rocker/tidyverse

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Set environmental variables
          command: |
            Rscript --vanilla \
              -e 'dsc = read.dcf("DESCRIPTION")' \
              -e 'cat(sprintf("export PKG_TARBALL=%s_%s.tar.gz\n", dsc[,"Package"], dsc[,"Version"]))' \
              -e 'cat(sprintf("export RCHECK_DIR=%s.Rcheck\n", dsc[,"Package"]))' \
              >> ${BASH_ENV} && \
            export PKG_VERSION=`Rscript --vanilla \
              -e 'dsc = read.dcf("DESCRIPTION")' \
              -e 'cat(dsc[,"Version"])'` && \
            export PKG_NAME=`Rscript --vanilla \
              -e 'dsc = read.dcf("DESCRIPTION")' \
              -e 'cat(dsc[,"Package"])'`

      - run:
          name: Install required packages from DESCRIPTION Imports
          command: |
            Rscript \
              -e 'packages = unlist(lapply(strsplit(read.dcf("DESCRIPTION")[,"Imports"], "\n"),' \
              -e 'function(x) strsplit(x, " ")))[c(TRUE, FALSE, FALSE)];' \
              -e 'for(package in packages) if (!requireNamespace(package, quietly = TRUE)) install.packages(package)'

      - run:
          name: Install required packages from DESCRIPTION Suggests
          command: |
            Rscript \
              -e 'packages = unlist(lapply(strsplit(read.dcf("DESCRIPTION")[,"Suggests"], "\n"),' \
              -e 'function(x) strsplit(x, " ")))[c(TRUE, FALSE, FALSE)];' \
              -e 'packages = Filter(function(x) x != "limma", packages);' \
              -e 'for(package in packages) if (!requireNamespace(package, quietly = TRUE)) install.packages(package)'

      - run:
          name: Install bioconductor-specific packages for Simphony
          command: |
            Rscript \
              -e 'BiocManager::install("limma")'

      - run:
          name: Build package
          command: R CMD build .

      - run:
          name: Check package
          command: R CMD check ${PKG_TARBALL} --no-manual

      - run:
          name: Check failures
          command: |
            Rscript -e "message(devtools::check_failures(path = '${PKG_NAME}.Rcheck'))"

      - run:
          name: Deploy to drat
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git clone https://github.com/hugheylab/drat;
              cd drat;
              Rscript -e "drat::insertPackage('../${PKG_TARBALL}', '.');"
              git commit -a -m "Updated ${PKG_NAME} to ${PKG_VERSION}";
              git push -q https://${GITHUB_TOKEN}@github.com/hugheylab/drat.git;
            else
              echo "Not deploying source to drat."
            fi
