version: 2
jobs:
  build:
    docker:
      - image: hugheylab/hugheyverse

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Set environmental variables
          command: |
            Rscript --vanilla \
              -e 'dsc <- read.dcf("DESCRIPTION")' \
              -e 'cat(sprintf("export PKG_TARBALL=%s_%s.tar.gz\n", dsc[,"Package"], dsc[,"Version"]))' \
              -e 'cat(sprintf("export RCHECK_DIR=%s.Rcheck\n", dsc[,"Package"]))' \
              >> ${BASH_ENV}

      - run:
          name: Install devtools and dependencies
          command: |
            Rscript \
              -e 'if (!requireNamespace("devtools", quietly = TRUE)) install.packages("devtools")' \
              -e 'devtools::install_deps(dependencies = TRUE)'

      - run:
          name: Build package
          command: R CMD build .

      - run:
          name: Check package
          command: R CMD check "${PKG_TARBALL}" --as-cran --no-manual

      - run:
          name: Check failures
          command: |
            Rscript -e "message(devtools::check_failures(path = '${RCHECK_DIR}'))"
