context('simulation')

test_that('Correct data types are generated by getSingleCondSim', {
  exprGroups = data.table::data.table(base = c(4), amp = c(4), phase = c(4), sd = c(0))
  simGse = getSingleCond(exprGroups, nGenes = 10, nRep = 2, period = 24,
                         interval = 4)
  
  expect_is(simGse$emat, 'matrix')
  expect_is(simGse$sm, 'data.table')
  expect_is(simGse$gm, 'data.table')

  rm(exprGroups, simGse)
})

test_that('Correct data types are generated by getTwoCondSim', {
  exprGroups = data.table::data.table(meanBase = c(4), dBase = c(1),
                                      meanAmp = c(4), dAmp = c(2),
                                      meanPhase = c(4), dPhase = c(3),
                                      meanSd = c(2), dSd = c(1))
  simGse = getTwoCond(exprGroups, nGenes = 10, nRep = 2, period = 24,
                      interval = 4)
  
  expect_is(simGse$emat, 'matrix')
  expect_is(simGse$sm, 'data.table')
  expect_is(simGse$gm, 'data.table')

  rm(exprGroups, simGse)
})

test_that('Single condition read counts can be simulated', {
  exprGroups = data.table::data.table(base = c(4), amp = c(4), phase = c(4), sd = c(0))
  simGse = getSingleCond(exprGroups, nGenes = 10, nRep = 2, period = 24,
                      interval = 4, method = 'nbinom')

  expect_is(simGse$emat, 'matrix')
  expect_is(simGse$sm, 'data.table')
  expect_is(simGse$gm, 'data.table')

  rm(exprGroups, simGse)
})